model:
  base_learning_rate: 1.0e-4
  target: sgm.models.diffusion.ResidualDiffusionEngine
  params:
    input_key: "label"
    mean_key: "cond_image"
    compile_model: False
    use_ema: True
    use_flash_attn2: False
    image_metrics: "evaluator"
    save_predict_targets: True
    save_predict_inputs: True
    predict_output_dirname: "restored"

    sigma_st_config:
      target: sgm.modules.diffusionmodules.sigma2st.EDMSigma2St
      params:
        alpha: 3.0

    denoiser_config:
      target: sgm.modules.diffusionmodules.denoiser.ResidualDenoiser
      params:
        scaling_config:
          target: sgm.modules.diffusionmodules.denoiser_scaling.ResidualEDMScaling
          params:
            sigma_input: 1.0
            sigma_mu: 1.0

    network_wrapper: "sgm.modules.diffusionmodules.wrappers.CloudRemovalWrapper"

    network_config:
      target: sgm.modules.diffusionmodules.k_diffusion.image_transformer.ImageTransformerDenoiserModelInterface
      params:
        in_channels: 6
        out_channels: 3
        patch_size: [4,4]
        widths: [64,128,256,512]
        depths: [2,2,2,2]
        d_ffs: [128,256,512,1024]
        self_attns: [
            {"type": "neighborhood", "d_head": 64, "kernel_size": 7},
            {"type": "neighborhood", "d_head": 64, "kernel_size": 7},
            {"type": "global", "d_head": 64},
            {"type": "global", "d_head": 64},
        ]
        dropout_rate: [0.0,0.0,0.0,0.1]
        mapping_depth: 2
        mapping_width: 512
        mapping_d_ff: 1024
        mapping_dropout_rate: 0.1

    conditioner_config:
      target: sgm.modules.GeneralConditioner
      params:
        emb_models:
          - is_trainable: True
            input_key: "cond_image"
            ucg_rate: 0.0
            target: sgm.modules.encoders.modules.IndentityEmbedder

    first_stage_config:
      target: sgm.models.autoencoder.IdentityFirstStage

    loss_fn_config:
      target: sgm.modules.diffusionmodules.importance_loss.ImportanceAwareResidualDiffusionLoss
      params:
        mask_key: "M"
        importance_weight: 4.0
        background_weight: 1.0
        mask_power: 1.0
        normalize_importance: True
        loss_weighting_config:
          target: sgm.modules.diffusionmodules.loss_weighting.ResidualEDMWeighting
          params:
            sigma_input: 1.0
            sigma_mu: 1.0
        sigma_sampler_config:
          target: sgm.modules.diffusionmodules.sigma_sampling.EDMSampling
          params:
            p_mean: -1.4
            p_std: 1.4

    sampler_config:
      target: sgm.modules.diffusionmodules.sampling.ResidualEulerEDMSampler
      params:
        num_steps: 4
        discretization_config:
          target: sgm.modules.diffusionmodules.discretizer.EDMDiscretization
          params:
            sigma_min: 0.001
            sigma_max: 100.0

    to_rgb_config:
      target: sgm.util.identity_to_rgb

data:
  target: sgm.data.base.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 8
    wrap: True

    predict:
      target: sgm.data.patches.cloud_patch_dataset.CloudRemovalPatchDataset
      params:
        dataset_root: "datasets/archive_random_10pct_experiment_crops_heavy_cloud"
        split: "test"
        require_mask: False
        allow_missing_label: True
        use_cloud_as_label_if_missing: True
        predict_output_dirname: "restored"

lightning:
  trainer:
    devices: "0,"
    precision: "16-mixed"
    num_sanity_val_steps: 0
    benchmark: True
